export class Cadastro{

    public cpf: string;
    public cnpj: string;
    public marketplaceRamoId: string;
    public nome: string;
    public origem: string;
    public matriz: boolean;
    public senha: string;
    public email: string;
    public tempoPreparo: number;
    public responsavelTelefone: number;
    public responsavelNome: string;
    public pedidoPrecificacaoTipo: string;
    public addUnidade: boolean;
    public endereco: string;
    public cep: string;
    public complemento: string;
    public valor1: number;
    public valor2: number;
    public valor3: number;
    public valor4: number;
    public valorBase: number;
    public valorChuvaFixo: number
    public valorCorrida: number;
    public valorKm: number;
    public valorTotal: number;
    public qtdEntregasDia: number;
}